import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.cards': 'Mes Cartes',
    'nav.createCard': 'Créer une Carte',
    'nav.profile': 'Mon Profil',
    'nav.login': 'Connexion',
    'nav.register': 'Inscription',
    'nav.logout': 'Déconnexion',
    'nav.newCard': 'Nouvelle carte',
    'nav.stats': 'Statistiques',
    'nav.analytics': 'Analytics',
    'nav.exportImport': 'Export/Import',
    
    // Account types
    'account.business': 'Compte Business',
    'account.personal': 'Compte Personnel',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.share': 'Partager',
    'common.like': 'J\'aime',
    'common.search': 'Rechercher',
    
    // Form labels
    'form.firstName': 'Prénom',
    'form.lastName': 'Nom',
    'form.email': 'Email',
    'form.password': 'Mot de passe',
    'form.phone': 'Téléphone',
    'form.title': 'Titre',
    'form.subtitle': 'Sous-titre',
    'form.description': 'Description',
    'form.website': 'Site web',
    'form.country': 'Pays',
    'form.city': 'Ville',
    
    // Messages
    'msg.loginSuccess': 'Connexion réussie !',
    'msg.logoutSuccess': 'Déconnexion réussie !',
    'msg.registerSuccess': 'Inscription réussie !',
    'msg.cardCreated': 'Carte créée avec succès !',
    'msg.cardUpdated': 'Carte mise à jour !',
    'msg.cardDeleted': 'Carte supprimée !',
    'msg.profileSaved': 'Profil sauvegardé',
    'msg.mustBeConnected': 'Vous devez être connecté pour aimer une carte',
    'msg.cardLiked': 'Carte likée !',
    
    // Home page
    'home.badge': 'Plateforme N°1 des cartes de visite digitales',
    'home.title': 'Révolutionnez vos',
    'home.titleHighlight': 'Cartes de Visite', 
    'home.subtitle': 'Créez, partagez et gérez vos cartes de visite numériques avec style. Une expérience professionnelle moderne qui impressionne vos contacts.',
    'home.createMagicCard': 'Créer ma carte magique',
    'home.startFree': 'Commencer gratuitement',
    'home.connect': 'Se connecter',
    'home.stats.cardsCreated': 'Cartes créées',
    'home.stats.satisfaction': 'Satisfaction client',
    'home.stats.support': 'Support disponible',
    'home.whyChoose': 'Pourquoi choisir Cardify ?',
    'home.whyChooseSubtitle': 'Découvrez les fonctionnalités qui font de Cardify la plateforme de référence',
    'home.instantCreation': 'Création Instantanée',
    'home.instantCreationDesc': 'Créez vos cartes en quelques clics avec notre interface intuitive et nos templates professionnels.',
    'home.guaranteedSecurity': 'Sécurité Garantie',
    'home.guaranteedSecurityDesc': 'Vos données sont protégées avec un chiffrement de niveau bancaire et une conformité RGPD.',
    'home.globalSharing': 'Partage Global',
    'home.globalSharingDesc': 'Partagez instantanément vos cartes via QR code, email, ou réseaux sociaux partout dans le monde.',
    'home.advancedAnalytics': 'Analytics Avancés',
    'home.advancedAnalyticsDesc': 'Suivez les vues, les interactions et optimisez l\'impact de vos cartes avec des statistiques détaillées.',
    'home.collaboration': 'Collaboration',
    'home.collaborationDesc': 'Travaillez en équipe, gérez les accès et créez des cartes cohérentes pour votre organisation.',
    'home.premiumTemplates': 'Templates Premium',
    'home.premiumTemplatesDesc': 'Accédez à plus de 100 templates professionnels conçus par des designers experts.',
    'home.cardCategories': 'Catégories de Cartes',
    'home.cardCategoriesSubtitle': 'Explorez notre collection de templates par secteur d\'activité',
    'home.business': 'Business',
    'home.businessDesc': 'Cartes professionnelles élégantes',
    'home.creative': 'Créatif',
    'home.creativeDesc': 'Designs artistiques et originaux',
    'home.tech': 'Tech',
    'home.techDesc': 'Moderne et innovant',
    'home.personal': 'Personnel',
    'home.personalDesc': 'Cartes personnelles uniques',
    'home.templates': 'templates',
    'home.discoverCommunity': 'Découvrez les créations de notre communauté',
    'home.searchPlaceholder': 'Rechercher par nom, secteur, style...',
    'home.communityCards': 'Cartes de la Communauté',
    'home.discoverCreations': 'Découvrez {count} créations inspirantes',
    'home.viewAllCards': 'Voir toutes les cartes',
    'home.noResults': 'Aucun résultat',
    'home.readyToStart': 'Prêt à commencer ?',
    'home.noResultsDesc': 'Essayez avec d\'autres mots-clés ou explorez nos catégories',
    'home.readyToStartDesc': 'Créez votre première carte de visite et rejoignez la communauté',
    'home.startNow': 'Commencer maintenant',
    'home.viewCard': 'Voir la carte',
    'home.cardNumber': 'Carte #',
    'home.viewOtherCards': 'Voir les {count} autres cartes',
    'home.readyToCreatePerfect': 'Prêt à créer votre carte parfaite ?',
    'home.joinProfessionals': 'Rejoignez plus de 50 000 professionnels qui utilisent Cardify pour impressionner leurs contacts',
    'home.createCardNow': 'Créer ma carte maintenant',
    'home.freeTrial': 'Essai gratuit - 30 jours',
    'home.exploreExamples': 'Explorer les exemples',
    
    // Login page
    'login.title': 'Connexion à Cardify',
    'login.noAccount': 'Pas encore de compte ?',
    'login.createAccount': 'Créer un compte',
    'login.emailLabel': 'Adresse email',
    'login.emailPlaceholder': 'votre@email.com',
    'login.passwordLabel': 'Mot de passe',
    'login.passwordPlaceholder': '••••••••',
    'login.signIn': 'Se connecter',
    'login.or': 'Ou',
    'login.backToHome': 'Retour à l\'accueil',
    'login.emailRequired': 'Email requis',
    'login.emailInvalid': 'Format d\'email invalide',
    'login.passwordRequired': 'Mot de passe requis',
    'login.passwordMin': 'Le mot de passe doit contenir au moins 7 caractères',
    
    // Register page
    'register.title': 'Créer un compte Cardify',
    'register.subtitle': 'Rejoignez la communauté Cardify et créez vos cartes de visite numériques',
    'register.haveAccount': 'Déjà un compte ?',
    'register.signIn': 'Se connecter',
    'register.firstNameRequired': 'Prénom requis',
    'register.lastNameRequired': 'Nom requis',
    'register.confirmPasswordRequired': 'Confirmation requis',
    'register.passwordMatch': 'Les mots de passe ne correspondent pas',
    'register.phoneRequired': 'Téléphone requis',
    'register.phoneInvalid': 'Format téléphone invalide (ex: 06-12345678)',
    'register.countryRequired': 'Pays requis',
    'register.cityRequired': 'Ville requis',
    'register.streetRequired': 'Rue requise',
    'register.houseNumberRequired': 'Numéro requis',
    'register.houseNumberInvalid': 'Numéro invalide',
    'register.zipRequired': 'Code postal requis',
    'register.zipInvalid': 'Code postal invalide (4-6 chiffres)',
    'register.confirmPasswordLabel': 'Confirmer le mot de passe',
    'register.phoneLabel': 'Téléphone',
    'register.addressSection': 'Adresse',
    'register.countryLabel': 'Pays',
    'register.cityLabel': 'Ville',
    'register.streetLabel': 'Rue',
    'register.houseNumberLabel': 'Numéro',
    'register.zipLabel': 'Code postal',
    'register.personalInfo': 'Informations personnelles',
    'register.securityInfo': 'Sécurité du compte',
    'register.addressInfo': 'Adresse et localisation',
    'register.accountType': 'Type de compte',
    'register.businessAccount': 'Compte Business (peut créer des cartes)',
    'register.createAccount': 'Créer mon compte',
    
    // Profile page
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos informations personnelles et préférences',
    'profile.unsavedChanges': 'Modifications non sauvegardées (sauvegarde automatique dans 2 secondes)',
    'profile.changeAvatar': 'Changer l\'avatar',
    'profile.businessAccount': 'Compte Business',
    'profile.personalAccount': 'Compte Personnel',
    'profile.avatarUrl': 'URL de l\'avatar',
    'profile.personalInfoSection': 'Informations personnelles',
    'profile.addressSection': 'Adresse',
    'profile.businessFeatures': 'Compte Business (accès aux fonctionnalités professionnelles)',
    'profile.loginRequired': 'Vous devez être connecté pour voir cette page.',
    'profile.saving': 'Sauvegarde...',
    'profile.saveNow': 'Sauvegarder maintenant',
    'profile.savedAuto': 'Profil sauvegardé automatiquement',
    'profile.savedDemo': 'Profil sauvegardé ! (mode démo)',
    'profile.saveError': 'Erreur lors de la sauvegarde du profil',
    'profile.stateRegion': 'État/Région',
    
    // Cards page
    'cards.title': 'Mes Cartes',
    'cards.subtitle': 'Gérez vos cartes de visite numériques',
    'cards.cardCount': 'carte',
    'cards.cardCountPlural': 'cartes',
    'cards.createCard': 'Créer une carte',
    'cards.searchPlaceholder': 'Rechercher dans vos cartes...',
    'cards.loading': 'Chargement de vos cartes...',
    'cards.loginRequired': 'Connexion requise',
    'cards.loginRequiredDesc': 'Vous devez être connecté pour voir vos cartes.',
    'cards.signIn': 'Se connecter',
    'cards.noCards': 'Aucune carte créée',
    'cards.noCardsDesc': 'Commencez par créer votre première carte de visite numérique.',
    'cards.createFirstCard': 'Créer ma première carte',
    'cards.noResults': 'Aucun résultat',
    'cards.noResultsDesc': 'Aucune carte ne correspond à votre recherche',
    'cards.view': 'Voir',
    'cards.likedDemo': 'Carte likée ! (mode démo)',
    'cards.liked': 'Carte likée !',
    'cards.likeError': 'Erreur lors du like',
    'cards.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette carte ?',
    'cards.deletedDemo': 'Carte supprimée ! (mode démo)',
    'cards.deleted': 'Carte supprimée !',
    'cards.deleteError': 'Fonctionnalité temporairement indisponible',
    
    // Create Card page
    'createCard.title': 'Créer une carte',
    'createCard.subtitle': 'Créez votre nouvelle carte de visite numérique professionnelle',
    'createCard.back': 'Retour',
    'createCard.loginRequired': 'Connexion requise',
    'createCard.loginRequiredDesc': 'Vous devez être connecté pour créer une carte.',
    'createCard.signIn': 'Se connecter',
    'createCard.businessRequired': 'Compte Business requis',
    'createCard.businessRequiredDesc': 'Vous devez avoir un compte Business pour créer des cartes de visite.',
    'createCard.upgradeToBusiness': 'Passer en Business',
    'createCard.backToCards': 'Retour aux cartes',
    'createCard.basicInfo': 'Informations de base',
    'createCard.cardTitle': 'Titre de la carte',
    'createCard.cardTitlePlaceholder': 'ex: Développeur Full-Stack',
    'createCard.cardSubtitle': 'Sous-titre',
    'createCard.cardSubtitlePlaceholder': 'ex: Spécialiste React & Node.js',
    'createCard.description': 'Description',
    'createCard.contact': 'Contact',
    'createCard.phoneLabel': 'Téléphone *',
    'createCard.phonePlaceholder': '+33 1 23 45 67 89',
    'createCard.emailLabel': 'Email *',
    'createCard.emailPlaceholder': 'contact@exemple.com',
    'createCard.websiteLabel': 'Site web',
    'createCard.websitePlaceholder': 'https://www.exemple.com',
    'createCard.address': 'Adresse',
    'createCard.image': 'Image (optionnel)',
    'createCard.selectImage': 'Choisir une image',
    'createCard.selectImageAria': 'Sélectionner une image pour la carte',
    'createCard.orEnterUrl': 'Ou entrez une URL d\'image ci-dessous',
    'createCard.imageUrl': 'URL de l\'image',
    'createCard.imageUrlPlaceholder': 'https://exemple.com/image.jpg',
    'createCard.imageAlt': 'Texte alternatif',
    'createCard.imageAltPlaceholder': 'Description de l\'image',
    'createCard.preview': 'Aperçu',
    'createCard.previewTitle': 'Titre de la carte',
    'createCard.previewSubtitle': 'Sous-titre',
    'createCard.cancel': 'Annuler',
    'createCard.creating': 'Création...',
    'createCard.create': 'Créer la carte',
    'createCard.success': 'Carte créée avec succès !',
    'createCard.error': 'Erreur lors de la création de la carte',
    'createCard.titleRequired': 'Le titre est requis',
    'createCard.subtitleRequired': 'Le sous-titre est requis',
    'createCard.descriptionRequired': 'La description est requise',
    'createCard.phoneRequired': 'Le téléphone est requis',
    'createCard.emailRequired': 'L\'email est requis',
    'createCard.countryRequired': 'Le pays est requis',
    'createCard.cityRequired': 'La ville est requise',
    'createCard.streetRequired': 'La rue est requise',
    'createCard.houseNumberRequired': 'Le numéro est requis',
    'createCard.businessOnly': 'Seuls les comptes Business peuvent créer des cartes',
    'createCard.upgradeAccount': 'Passer en compte Business',
    'createCard.titleLabel': 'Titre *',
    'createCard.titlePlaceholder': 'Nom de votre entreprise ou service',
    'createCard.subtitleLabel': 'Sous-titre *',
    'createCard.subtitlePlaceholder': 'Votre fonction ou spécialité',
    'createCard.descriptionLabel': 'Description *',
    'createCard.descriptionPlaceholder': 'Décrivez votre activité, vos services...',

    // CardDetail Page
    'cardDetail.loading': 'Chargement...',
    'cardDetail.notFound': 'Carte non trouvée',
    'cardDetail.notFoundMessage': 'Cette carte n\'existe pas ou a été supprimée.',
    'cardDetail.backToCards': 'Retour aux cartes',
    'cardDetail.description': 'Description',
    'cardDetail.contact': 'Contact',
    'cardDetail.phone': 'Téléphone',
    'cardDetail.email': 'Email',
    'cardDetail.website': 'Site web',
    'cardDetail.address': 'Adresse',
    'cardDetail.owner': 'Propriétaire',
    'cardDetail.businessAccount': 'Compte Business',
    'cardDetail.personalAccount': 'Compte Personnel',
    'cardDetail.statistics': 'Statistiques',
    'cardDetail.likes': 'Likes',
    'cardDetail.createdOn': 'Créée le',
    'cardDetail.actions': 'Actions',
    'cardDetail.shareCard': 'Partager cette carte',
    'cardDetail.likeCard': 'Liker cette carte',
    'cardDetail.unlikeCard': 'Retirer le like',
    'cardDetail.editCard': 'Modifier la carte',
    'cardDetail.deleteCard': 'Supprimer la carte',
    'cardDetail.loginToLike': 'Vous devez être connecté pour liker une carte',
    'cardDetail.likeRemoved': 'Like retiré',
    'cardDetail.cardLiked': 'Carte likée !',
    'cardDetail.likeError': 'Erreur lors du like',
    'cardDetail.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette carte ? Cette action est irréversible.',
    'cardDetail.deleteSuccess': 'Carte supprimée avec succès',
    'cardDetail.deleteError': 'Erreur lors de la suppression',
    'cardDetail.linkCopied': 'Lien copié dans le presse-papiers',
    'cardDetail.shareError': 'Erreur lors du partage',
    'cardDetail.loadError': 'Erreur lors du chargement de la carte',
    'cardDetail.user': 'Utilisateur',

    // EditCard Page
    'editCard.title': 'Modifier la carte',
    'editCard.subtitle': 'Modifiez les informations de votre carte de visite',
    'editCard.back': 'Retour',
    'editCard.loginRequired': 'Connexion requise',
    'editCard.loginRequiredDesc': 'Vous devez être connecté pour modifier une carte.',
    'editCard.signIn': 'Se connecter',
    'editCard.loading': 'Chargement de la carte...',
    'editCard.basicInfo': 'Informations de base',
    'editCard.titleLabel': 'Titre de la carte *',
    'editCard.titlePlaceholder': 'ex: Développeur Full-Stack',
    'editCard.subtitleLabel': 'Sous-titre *',
    'editCard.subtitlePlaceholder': 'ex: Spécialiste React & Node.js',
    'editCard.descriptionLabel': 'Description *',
    'editCard.descriptionPlaceholder': 'Décrivez vos services et compétences...',
    'editCard.contact': 'Contact',
    'editCard.phoneLabel': 'Téléphone *',
    'editCard.phonePlaceholder': '06-12345678',
    'editCard.emailLabel': 'Email *',
    'editCard.emailPlaceholder': 'contact@exemple.com',
    'editCard.websiteLabel': 'Site web',
    'editCard.websitePlaceholder': 'https://monsite.com',
    'editCard.address': 'Adresse',
    'editCard.image': 'Image (optionnel)',
    'editCard.selectImage': 'Choisir une nouvelle image',
    'editCard.selectImageAria': 'Sélectionner une nouvelle image pour la carte',
    'editCard.orModifyUrl': 'Ou modifiez l\'URL d\'image ci-dessous',
    'editCard.imageUrl': 'URL de l\'image',
    'editCard.imageUrlPlaceholder': 'https://exemple.com/image.jpg',
    'editCard.imageAlt': 'Texte alternatif',
    'editCard.imageAltPlaceholder': 'Description de l\'image',
    'editCard.cancel': 'Annuler',
    'editCard.saving': 'Modification...',
    'editCard.save': 'Sauvegarder',
    'editCard.preview': 'Aperçu',
    'editCard.previewTitle': 'Titre de la carte',
    'editCard.previewSubtitle': 'Sous-titre',
    'editCard.success': 'Carte modifiée avec succès !',
    'editCard.successDemo': 'Carte modifiée avec succès ! (mode démo)',
    'editCard.error': 'Erreur lors de la modification',
    'editCard.formError': 'Veuillez corriger les erreurs dans le formulaire',
    'editCard.checkDataError': 'Vérifiez vos données et réessayez',
    'editCard.titleRequired': 'Le titre est requis',
    'editCard.subtitleRequired': 'Le sous-titre est requis',
    'editCard.descriptionRequired': 'La description est requise',
    'editCard.phoneRequired': 'Le téléphone est requis',
    'editCard.phoneInvalid': 'Format de téléphone invalide (ex: 06-12345678)',
    'editCard.emailRequired': 'L\'email est requis',
    'editCard.emailInvalid': 'Format d\'email invalide',
    'editCard.countryRequired': 'Le pays est requis',
    'editCard.cityRequired': 'La ville est requise',
    'editCard.streetRequired': 'La rue est requise',
    'editCard.houseNumberRequired': 'Le numéro de maison est requis',
    'editCard.loadError': 'Erreur lors du chargement de la carte',
    'editCard.notAuthorized': 'Vous n\'êtes pas autorisé à modifier cette carte',

    // Loading & UI Components
    'loading.default': 'Chargement...',
    'loading.page': 'Chargement de la page...',
    'loading.data': 'Chargement des données...',
    'loading.saving': 'Sauvegarde en cours...',
    'loading.processing': 'Traitement en cours...',

    // NotFound Page
    'notFound.title': 'Page introuvable',
    'notFound.message': 'Désolé, la page que vous recherchez n\'existe pas ou a été déplacée.',
    'notFound.backHome': 'Retour à l\'accueil',
    'notFound.backPrevious': 'Page précédente',
    'notFound.popularPages': 'Pages les plus visitées :',
    'notFound.myCards': 'Mes Cartes',
    'notFound.createCard': 'Créer une Carte',
    'notFound.myProfile': 'Mon Profil',

    // CardDetail Phone
    'cardDetail.phoneCopied': 'Numéro de téléphone copié!',

    // AdminDashboard
    'admin.title': 'Dashboard Administrateur',
    'admin.subtitle': 'Gestion et surveillance de la plateforme Cardify',
    'admin.accessDenied': 'Accès Refusé',
    'admin.adminOnly': 'Seuls les administrateurs peuvent accéder à cette page.',
    'admin.loading': 'Chargement du dashboard administrateur...',
    'admin.totalUsers': 'Utilisateurs totaux',
    'admin.activeUsers': 'Utilisateurs actifs',
    'admin.totalCards': 'Cartes totales',
    'admin.recentSignups': 'Nouvelles inscriptions',
    'admin.userManagement': 'Gestion des Utilisateurs',
    'admin.refresh': 'Actualiser',
    'admin.searchUsers': 'Rechercher un utilisateur...',
    'admin.filterUsers': 'Filtrer les utilisateurs par statut',
    'admin.allUsers': 'Tous les utilisateurs',
    'admin.activeOnly': 'Utilisateurs actifs',
    'admin.inactiveOnly': 'Utilisateurs inactifs',
    'admin.user': 'Utilisateur',
    'admin.type': 'Type',
    'admin.status': 'Statut',
    'admin.cards': 'Cartes',
    'admin.lastLogin': 'Dernière connexion',
    'admin.actions': 'Actions',
    'admin.business': 'Business',
    'admin.personal': 'Personnel',
    'admin.active': 'Actif',
    'admin.inactive': 'Inactif',
    'admin.never': 'Jamais',
    'admin.admin': 'Admin',
    'admin.activityLog': 'Journal d\'Activité',
    'admin.noActivity': 'Aucune activité récente',
    'admin.userActivated': 'activé',
    'admin.userDeactivated': 'désactivé',
    'admin.userDeleted': 'supprimé',
    'admin.actionSuccess': 'Utilisateur {action} avec succès',
    'admin.actionError': 'Impossible d\'effectuer cette action',
    'admin.newUserCreated': 'Nouvel utilisateur créé',
    'admin.newCardCreated': 'Nouvelle carte créée',
    'admin.userLogin': 'Connexion utilisateur',
    'admin.adminAction': 'Action administrateur effectuée',

    // Export/Import Page
    'exportImport.title': 'Export/Import',
    'exportImport.loadError': 'Erreur',
    'exportImport.loadErrorMsg': 'Impossible de charger vos cartes',
    'exportImport.noCardsTitle': 'Aucune carte à exporter',
    'exportImport.noCardsMsg': 'Vous devez avoir au moins une carte pour l\'export',
    'exportImport.exportSuccess': 'Export réussi',
    'exportImport.exportSuccessMsg': '{count} cartes exportées au format {format}',
    'exportImport.importPartial': 'Import partiel',
    'exportImport.importPartialMsg': '{count} erreurs lors de l\'import',
    'exportImport.importError': 'Erreur d\'import',
    'exportImport.importErrorMsg': 'Erreur lors de l\'import',
    'exportImport.chooseFile': 'Choisir un fichier JSON à importer',
    'exportImport.unknownError': 'Erreur inconnue',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.cards': 'My Cards',
    'nav.createCard': 'Create Card',
    'nav.profile': 'My Profile',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.newCard': 'New Card',
    'nav.stats': 'Statistics',
    'nav.analytics': 'Analytics',
    'nav.exportImport': 'Export/Import',
    
    // Account types
    'account.business': 'Business Account',
    'account.personal': 'Personal Account',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.search': 'Search',
    
    // Form labels
    'form.firstName': 'First Name',
    'form.lastName': 'Last Name',
    'form.email': 'Email',
    'form.password': 'Password',
    'form.phone': 'Phone',
    'form.title': 'Title',
    'form.subtitle': 'Subtitle',
    'form.description': 'Description',
    'form.website': 'Website',
    'form.country': 'Country',
    'form.city': 'City',
    
    // Messages
    'msg.loginSuccess': 'Login successful!',
    'msg.logoutSuccess': 'Logout successful!',
    'msg.registerSuccess': 'Registration successful!',
    'msg.cardCreated': 'Card created successfully!',
    'msg.cardUpdated': 'Card updated!',
    'msg.cardDeleted': 'Card deleted!',
    'msg.profileSaved': 'Profile saved',
    'msg.mustBeConnected': 'You must be logged in to like a card',
    'msg.cardLiked': 'Card liked!',
    
    // Home page
    'home.badge': '#1 Digital Business Card Platform',
    'home.title': 'Revolutionize your',
    'home.titleHighlight': 'Business Cards', 
    'home.subtitle': 'Create, share and manage your digital business cards with style. A modern professional experience that impresses your contacts.',
    'home.createMagicCard': 'Create my magic card',
    'home.startFree': 'Start for free',
    'home.connect': 'Sign in',
    'home.stats.cardsCreated': 'Cards created',
    'home.stats.satisfaction': 'Customer satisfaction',
    'home.stats.support': 'Support available',
    'home.whyChoose': 'Why choose Cardify?',
    'home.whyChooseSubtitle': 'Discover the features that make Cardify the reference platform',
    'home.instantCreation': 'Instant Creation',
    'home.instantCreationDesc': 'Create your cards in a few clicks with our intuitive interface and professional templates.',
    'home.guaranteedSecurity': 'Guaranteed Security',
    'home.guaranteedSecurityDesc': 'Your data is protected with bank-level encryption and GDPR compliance.',
    'home.globalSharing': 'Global Sharing',
    'home.globalSharingDesc': 'Share your cards instantly via QR code, email, or social networks worldwide.',
    'home.advancedAnalytics': 'Advanced Analytics',
    'home.advancedAnalyticsDesc': 'Track views, interactions and optimize your cards\' impact with detailed statistics.',
    'home.collaboration': 'Collaboration',
    'home.collaborationDesc': 'Work as a team, manage access and create consistent cards for your organization.',
    'home.premiumTemplates': 'Premium Templates',
    'home.premiumTemplatesDesc': 'Access over 100 professional templates designed by expert designers.',
    'home.cardCategories': 'Card Categories',
    'home.cardCategoriesSubtitle': 'Explore our template collection by industry',
    'home.business': 'Business',
    'home.businessDesc': 'Elegant professional cards',
    'home.creative': 'Creative',
    'home.creativeDesc': 'Artistic and original designs',
    'home.tech': 'Tech',
    'home.techDesc': 'Modern and innovative',
    'home.personal': 'Personal',
    'home.personalDesc': 'Unique personal cards',
    'home.templates': 'templates',
    'home.discoverCommunity': 'Discover our community creations',
    'home.searchPlaceholder': 'Search by name, industry, style...',
    'home.communityCards': 'Community Cards',
    'home.discoverCreations': 'Discover {count} inspiring creations',
    'home.viewAllCards': 'View all cards',
    'home.noResults': 'No results',
    'home.readyToStart': 'Ready to start?',
    'home.noResultsDesc': 'Try with other keywords or explore our categories',
    'home.readyToStartDesc': 'Create your first business card and join the community',
    'home.startNow': 'Start now',
    'home.viewCard': 'View card',
    'home.cardNumber': 'Card #',
    'home.viewOtherCards': 'View {count} other cards',
    'home.readyToCreatePerfect': 'Ready to create your perfect card?',
    'home.joinProfessionals': 'Join over 50,000 professionals who use Cardify to impress their contacts',
    'home.createCardNow': 'Create my card now',
    'home.freeTrial': 'Free trial - 30 days',
    'home.exploreExamples': 'Explore examples',
    
    // Login page
    'login.title': 'Sign in to Cardify',
    'login.noAccount': 'Don\'t have an account?',
    'login.createAccount': 'Create account',
    'login.emailLabel': 'Email address',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.signIn': 'Sign in',
    'login.or': 'Or',
    'login.backToHome': 'Back to home',
    'login.emailRequired': 'Email required',
    'login.emailInvalid': 'Invalid email format',
    'login.passwordRequired': 'Password required',
    'login.passwordMin': 'Password must be at least 7 characters',
    
    // Register page
    'register.title': 'Create Cardify Account',
    'register.subtitle': 'Join the Cardify community and create your digital business cards',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.firstNameRequired': 'First name required',
    'register.lastNameRequired': 'Last name required',
    'register.confirmPasswordRequired': 'Confirmation required',
    'register.passwordMatch': 'Passwords do not match',
    'register.phoneRequired': 'Phone required',
    'register.phoneInvalid': 'Invalid phone format (ex: 06-12345678)',
    'register.countryRequired': 'Country required',
    'register.cityRequired': 'City required',
    'register.streetRequired': 'Street required',
    'register.houseNumberRequired': 'Number required',
    'register.houseNumberInvalid': 'Invalid number',
    'register.zipRequired': 'Zip code required',
    'register.zipInvalid': 'Invalid zip code (4-6 digits)',
    'register.confirmPasswordLabel': 'Confirm password',
    'register.phoneLabel': 'Phone',
    'register.addressSection': 'Address',
    'register.countryLabel': 'Country',
    'register.cityLabel': 'City',
    'register.streetLabel': 'Street',
    'register.houseNumberLabel': 'Number',
    'register.zipLabel': 'Zip code',
    'register.personalInfo': 'Personal Information',
    'register.securityInfo': 'Account Security',
    'register.addressInfo': 'Address and Location',
    'register.accountType': 'Account type',
    'register.businessAccount': 'Business Account (can create cards)',
    'register.createAccount': 'Create my account',
    
    // Profile page
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.unsavedChanges': 'Unsaved changes (auto-save in 2 seconds)',
    'profile.changeAvatar': 'Change avatar',
    'profile.businessAccount': 'Business Account',
    'profile.personalAccount': 'Personal Account',
    'profile.avatarUrl': 'Avatar URL',
    'profile.personalInfoSection': 'Personal Information',
    'profile.addressSection': 'Address',
    'profile.businessFeatures': 'Business Account (access to professional features)',
    'profile.loginRequired': 'You must be logged in to view this page.',
    'profile.saving': 'Saving...',
    'profile.saveNow': 'Save now',
    'profile.savedAuto': 'Profile saved automatically',
    'profile.savedDemo': 'Profile saved! (demo mode)',
    'profile.saveError': 'Error saving profile',
    'profile.stateRegion': 'State/Region',
    
    // Cards page
    'cards.title': 'My Cards',
    'cards.subtitle': 'Manage your digital business cards',
    'cards.cardCount': 'card',
    'cards.cardCountPlural': 'cards',
    'cards.createCard': 'Create a card',
    'cards.searchPlaceholder': 'Search in your cards...',
    'cards.loading': 'Loading your cards...',
    'cards.loginRequired': 'Login Required',
    'cards.loginRequiredDesc': 'You must be logged in to view your cards.',
    'cards.signIn': 'Sign in',
    'cards.noCards': 'No cards created',
    'cards.noCardsDesc': 'Start by creating your first digital business card.',
    'cards.createFirstCard': 'Create my first card',
    'cards.noResults': 'No results',
    'cards.noResultsDesc': 'No cards match your search for',
    'cards.view': 'View',
    'cards.likedDemo': 'Card liked! (demo mode)',
    'cards.liked': 'Card liked!',
    'cards.likeError': 'Error liking card',
    'cards.deleteConfirm': 'Are you sure you want to delete this card?',
    'cards.deletedDemo': 'Card deleted! (demo mode)',
    'cards.deleted': 'Card deleted!',
    'cards.deleteError': 'Feature temporarily unavailable',
    
    // Create Card page
    'createCard.title': 'Create a card',
    'createCard.subtitle': 'Create your new professional digital business card',
    'createCard.back': 'Back',
    'createCard.loginRequired': 'Login Required',
    'createCard.loginRequiredDesc': 'You must be logged in to create a card.',
    'createCard.signIn': 'Sign in',
    'createCard.businessRequired': 'Business Account Required',
    'createCard.businessRequiredDesc': 'You must have a Business account to create business cards.',
    'createCard.upgradeToBusiness': 'Upgrade to Business',
    'createCard.backToCards': 'Back to cards',
    'createCard.basicInfo': 'Basic information',
    'createCard.cardTitle': 'Card title',
    'createCard.cardTitlePlaceholder': 'e.g.: Full-Stack Developer',
    'createCard.cardSubtitle': 'Subtitle',
    'createCard.cardSubtitlePlaceholder': 'e.g.: React & Node.js Specialist',
    'createCard.description': 'Description',
    'createCard.descriptionPlaceholder': 'Describe your services and skills...',
    'createCard.contact': 'Contact',
    'createCard.website': 'Website',
    'createCard.websitePlaceholder': 'https://mysite.com',
    'createCard.address': 'Address',
    'createCard.image': 'Image (optional)',
    'createCard.selectImage': 'Choose an image',
    'createCard.selectImageAria': 'Select an image for the card',
    'createCard.orEnterUrl': 'Or enter an image URL below',
    'createCard.imageUrl': 'Image URL',
    'createCard.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'createCard.imageAlt': 'Alt text',
    'createCard.imageAltPlaceholder': 'Image description',
    'createCard.preview': 'Preview',
    'createCard.previewTitle': 'Card title',
    'createCard.previewSubtitle': 'Subtitle',
    'createCard.cancel': 'Cancel',
    'createCard.creating': 'Creating...',
    'createCard.create': 'Create card',
    'createCard.formError': 'Please correct the errors in the form',
    'createCard.createdDemo': 'Card created successfully! (demo mode)',
    'createCard.created': 'Card created successfully!',
    'createCard.checkDataError': 'Check your data and try again',
    'createCard.titleRequired': 'Title is required',
    'createCard.subtitleRequired': 'Subtitle is required',
    'createCard.descriptionRequired': 'Description is required',
    'createCard.phoneRequired': 'Phone is required',
    'createCard.phoneInvalid': 'Invalid phone format (e.g.: 06-12345678)',
    'createCard.emailRequired': 'Email is required',
    'createCard.emailInvalid': 'Invalid email format',
    'createCard.countryRequired': 'Country is required',
    'createCard.cityRequired': 'City is required',
    'createCard.streetRequired': 'Street is required',
    'createCard.houseNumberRequired': 'House number is required',

    // CardDetail Page
    'cardDetail.loading': 'Loading...',
    'cardDetail.notFound': 'Card not found',
    'cardDetail.notFoundMessage': 'This card does not exist or has been deleted.',
    'cardDetail.backToCards': 'Back to cards',
    'cardDetail.description': 'Description',
    'cardDetail.contact': 'Contact',
    'cardDetail.phone': 'Phone',
    'cardDetail.email': 'Email',
    'cardDetail.website': 'Website',
    'cardDetail.address': 'Address',
    'cardDetail.owner': 'Owner',
    'cardDetail.businessAccount': 'Business Account',
    'cardDetail.personalAccount': 'Personal Account',
    'cardDetail.statistics': 'Statistics',
    'cardDetail.likes': 'Likes',
    'cardDetail.createdOn': 'Created on',
    'cardDetail.actions': 'Actions',
    'cardDetail.shareCard': 'Share this card',
    'cardDetail.likeCard': 'Like this card',
    'cardDetail.unlikeCard': 'Remove like',
    'cardDetail.editCard': 'Edit card',
    'cardDetail.deleteCard': 'Delete card',
    'cardDetail.loginToLike': 'You must be logged in to like a card',
    'cardDetail.likeRemoved': 'Like removed',
    'cardDetail.cardLiked': 'Card liked!',
    'cardDetail.likeError': 'Error liking card',
    'cardDetail.deleteConfirm': 'Are you sure you want to delete this card? This action is irreversible.',
    'cardDetail.deleteSuccess': 'Card deleted successfully',
    'cardDetail.deleteError': 'Error deleting card',
    'cardDetail.linkCopied': 'Link copied to clipboard',
    'cardDetail.shareError': 'Error sharing card',
    'cardDetail.loadError': 'Error loading card',
    'cardDetail.user': 'User',

    // EditCard Page
    'editCard.title': 'Edit Card',
    'editCard.subtitle': 'Modify your business card information',
    'editCard.back': 'Back',
    'editCard.loginRequired': 'Login Required',
    'editCard.loginRequiredDesc': 'You must be logged in to edit a card.',
    'editCard.signIn': 'Sign in',
    'editCard.loading': 'Loading card...',
    'editCard.basicInfo': 'Basic information',
    'editCard.titleLabel': 'Card title *',
    'editCard.titlePlaceholder': 'e.g.: Full-Stack Developer',
    'editCard.subtitleLabel': 'Subtitle *',
    'editCard.subtitlePlaceholder': 'e.g.: React & Node.js Specialist',
    'editCard.descriptionLabel': 'Description *',
    'editCard.descriptionPlaceholder': 'Describe your services and skills...',
    'editCard.contact': 'Contact',
    'editCard.phoneLabel': 'Phone *',
    'editCard.phonePlaceholder': '06-12345678',
    'editCard.emailLabel': 'Email *',
    'editCard.emailPlaceholder': 'contact@example.com',
    'editCard.websiteLabel': 'Website',
    'editCard.websitePlaceholder': 'https://mysite.com',
    'editCard.address': 'Address',
    'editCard.image': 'Image (optional)',
    'editCard.selectImage': 'Choose a new image',
    'editCard.selectImageAria': 'Select a new image for the card',
    'editCard.orModifyUrl': 'Or modify the image URL below',
    'editCard.imageUrl': 'Image URL',
    'editCard.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'editCard.imageAlt': 'Alt text',
    'editCard.imageAltPlaceholder': 'Image description',
    'editCard.cancel': 'Cancel',
    'editCard.saving': 'Saving...',
    'editCard.save': 'Save',
    'editCard.preview': 'Preview',
    'editCard.previewTitle': 'Card title',
    'editCard.previewSubtitle': 'Subtitle',
    'editCard.success': 'Card updated successfully!',
    'editCard.successDemo': 'Card updated successfully! (demo mode)',
    'editCard.error': 'Error updating card',
    'editCard.formError': 'Please correct the errors in the form',
    'editCard.checkDataError': 'Check your data and try again',
    'editCard.titleRequired': 'Title is required',
    'editCard.subtitleRequired': 'Subtitle is required',
    'editCard.descriptionRequired': 'Description is required',
    'editCard.phoneRequired': 'Phone is required',
    'editCard.phoneInvalid': 'Invalid phone format (e.g.: 06-12345678)',
    'editCard.emailRequired': 'Email is required',
    'editCard.emailInvalid': 'Invalid email format',
    'editCard.countryRequired': 'Country is required',
    'editCard.cityRequired': 'City is required',
    'editCard.streetRequired': 'Street is required',
    'editCard.houseNumberRequired': 'House number is required',
    'editCard.loadError': 'Error loading card',
    'editCard.notAuthorized': 'You are not authorized to edit this card',

    // Loading & UI Components
    'loading.default': 'Loading...',
    'loading.page': 'Loading page...',
    'loading.data': 'Loading data...',
    'loading.saving': 'Saving...',
    'loading.processing': 'Processing...',

    // NotFound Page
    'notFound.title': 'Page not found',
    'notFound.message': 'Sorry, the page you are looking for does not exist or has been moved.',
    'notFound.backHome': 'Back to home',
    'notFound.backPrevious': 'Previous page',
    'notFound.popularPages': 'Most visited pages:',
    'notFound.myCards': 'My Cards',
    'notFound.createCard': 'Create Card',
    'notFound.myProfile': 'My Profile',

    // CardDetail Phone
    'cardDetail.phoneCopied': 'Phone number copied!',

    // AdminDashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Cardify platform management and monitoring',
    'admin.accessDenied': 'Access Denied',
    'admin.adminOnly': 'Only administrators can access this page.',
    'admin.loading': 'Loading admin dashboard...',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active Users',
    'admin.totalCards': 'Total Cards',
    'admin.recentSignups': 'Recent Signups',
    'admin.userManagement': 'User Management',
    'admin.refresh': 'Refresh',
    'admin.searchUsers': 'Search for a user...',
    'admin.filterUsers': 'Filter users by status',
    'admin.allUsers': 'All users',
    'admin.activeOnly': 'Active users',
    'admin.inactiveOnly': 'Inactive users',
    'admin.user': 'User',
    'admin.type': 'Type',
    'admin.status': 'Status',
    'admin.cards': 'Cards',
    'admin.lastLogin': 'Last Login',
    'admin.actions': 'Actions',
    'admin.business': 'Business',
    'admin.personal': 'Personal',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.never': 'Never',
    'admin.admin': 'Admin',
    'admin.activityLog': 'Activity Log',
    'admin.noActivity': 'No recent activity',
    'admin.userActivated': 'activated',
    'admin.userDeactivated': 'deactivated',
    'admin.userDeleted': 'deleted',
    'admin.actionSuccess': 'User {action} successfully',
    'admin.actionError': 'Unable to perform this action',
    'admin.newUserCreated': 'New user created',
    'admin.newCardCreated': 'New card created',
    'admin.userLogin': 'User login',
    'admin.adminAction': 'Admin action performed',

    // Export/Import Page
    'exportImport.title': 'Export/Import',
    'exportImport.loadError': 'Error',
    'exportImport.loadErrorMsg': 'Unable to load your cards',
    'exportImport.noCardsTitle': 'No cards to export',
    'exportImport.noCardsMsg': 'You need at least one card to export',
    'exportImport.exportSuccess': 'Export successful',
    'exportImport.exportSuccessMsg': '{count} cards exported in {format} format',
    'exportImport.importPartial': 'Partial import',
    'exportImport.importPartialMsg': '{count} errors during import',
    'exportImport.importError': 'Import error',
    'exportImport.importErrorMsg': 'Error during import',
    'exportImport.chooseFile': 'Choose a JSON file to import',
    'exportImport.unknownError': 'Unknown error',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.cards': 'הכרטיסים שלי',
    'nav.createCard': 'יצירת כרטיס',
    'nav.profile': 'הפרופיל שלי',
    'nav.login': 'התחברות',
    'nav.register': 'הרשמה',
    'nav.logout': 'התניתקות',
    'nav.newCard': 'כרטיס חדש',
    'nav.stats': 'סטטיסטיקות',
    'nav.analytics': 'אנליטיקה',
    'nav.exportImport': 'יצוא/יבוא',
    
    // Account types
    'account.business': 'חשבון עסקי',
    'account.personal': 'חשבון אישי',
    
    // Common
    'common.loading': 'טוען...',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.cancel': 'ביטול',
    'common.save': 'שמירה',
    'common.delete': 'מחיקה',
    'common.edit': 'עריכה',
    'common.share': 'שיתוף',
    'common.like': 'אהבתי',
    'common.search': 'חיפוש',
    
    // Form labels
    'form.firstName': 'שם פרטי',
    'form.lastName': 'שם משפחה',
    'form.email': 'אימייל',
    'form.password': 'סיסמה',
    'form.phone': 'טלפון',
    'form.title': 'כותרת',
    'form.subtitle': 'כותרת משנה',
    'form.description': 'תיאור',
    'form.website': 'אתר אינטרנט',
    'form.country': 'מדינה',
    'form.city': 'עיר',
    
    // Messages
    'msg.loginSuccess': 'התחברות בוצעה בהצלחה!',
    'msg.logoutSuccess': 'התניתקות בוצעה בהצלחה!',
    'msg.registerSuccess': 'הרשמה בוצעה בהצלחה!',
    'msg.cardCreated': 'הכרטיס נוצר בהצלחה!',
    'msg.cardUpdated': 'הכרטיס עודכן!',
    'msg.cardDeleted': 'הכרטיס נמחק!',
    'msg.profileSaved': 'הפרופיל נשמר',
    'msg.mustBeConnected': 'עליך להתחבר כדי לאהוב כרטיס',
    'msg.cardLiked': 'הכרטיס זכה לאהבה!',

    // Home page
    'home.badge': 'פלטפורמת כרטיסי ביקור דיגיטליים מס\' 1',
    'home.title': 'מהפכה בכרטיסי',
    'home.titleHighlight': 'הביקור שלכם',
    'home.subtitle': 'צרו, שתפו ונהלו את כרטיסי הביקור הדיגיטליים שלכם בסטייל. חוויה מקצועית מודרנית שתרשים את הקשרים שלכם.',
    'home.createMagicCard': 'ליצור את הכרטיס הקסום שלי',
    'home.startFree': 'התחל בחינם',
    'home.connect': 'התחבר',
    'home.stats.cardsCreated': 'כרטיסים נוצרו',
    'home.stats.satisfaction': 'שביעות רצון לקוחות',
    'home.stats.support': 'תמיכה זמינה',
    'home.whyChoose': 'למה לבחור ב-Cardify?',
    'home.whyChooseSubtitle': 'גלו את התכונות שהופכות את Cardify לפלטפורמת הייחוס',
    'home.instantCreation': 'יצירה מיידית',
    'home.instantCreationDesc': 'צרו את הכרטיסים שלכם במספר קליקים עם הממשק האינטואיטיבי והתבניות המקצועיות שלנו.',
    'home.guaranteedSecurity': 'אבטחה מובטחת',
    'home.guaranteedSecurityDesc': 'הנתונים שלכם מוגנים עם הצפנה ברמת בנק ותאימות GDPR.',
    'home.globalSharing': 'שיתוף גלובלי',
    'home.globalSharingDesc': 'שתפו את הכרטיסים שלכם באופן מיידי באמצעות QR קוד, אימייל, או רשתות חברתיות בכל העולם.',
    'home.advancedAnalytics': 'אנליטיקה מתקדמת',
    'home.advancedAnalyticsDesc': 'עקבו אחר צפיות, אינטראקציות ותמטבו את ההשפעה של הכרטיסים שלכם עם סטטיסטיקות מפורטות.',
    'home.collaboration': 'שיתוף פעולה',
    'home.collaborationDesc': 'עבדו כצוות, נהלו גישות ותצרו כרטיסים עקביים לארגון שלכם.',
    'home.premiumTemplates': 'תבניות פרימיום',
    'home.premiumTemplatesDesc': 'גישה לכמעט 100 תבניות מקצועיות שעוצבו על ידי מעצבים מומחים.',
    'home.cardCategories': 'קטגוריות כרטיסים',
    'home.cardCategoriesSubtitle': 'חקרו את אוסף התבניות שלנו לפי תחום פעילות',
    'home.business': 'עסקי',
    'home.businessDesc': 'כרטיסים מקצועיים אלגנטיים',
    'home.creative': 'יצירתי',
    'home.creativeDesc': 'עיצובים אמנותיים ומקוריים',
    'home.tech': 'טכנולוגי',
    'home.techDesc': 'מודרני וחדשני',
    'home.personal': 'אישי',
    'home.personalDesc': 'כרטיסים אישיים ייחודיים',
    'home.templates': 'תבניות',
    'home.discoverCommunity': 'גלו את יצירות הקהילה שלנו',
    'home.searchPlaceholder': 'חפש לפי שם, תחום, סגנון...',
    'home.communityCards': 'כרטיסי הקהילה',
    'home.discoverCreations': 'גלו {count} יצירות מעוררות השראה',
    'home.viewAllCards': 'צפה בכל הכרטיסים',
    'home.noResults': 'אין תוצאות',
    'home.readyToStart': 'מוכנים להתחיל?',
    'home.noResultsDesc': 'נסו עם מילות מפתח אחרות או חקרו את הקטגוריות שלנו',
    'home.readyToStartDesc': 'צרו את כרטיס הביקור הראשון שלכם והצטרפו לקהילה',
    'home.startNow': 'התחל עכשיו',
    'home.viewCard': 'צפה בכרטיס',
    'home.cardNumber': 'כרטיס #',
    'home.viewOtherCards': 'צפה ב-{count} כרטיסים אחרים',
    'home.readyToCreatePerfect': 'מוכנים ליצור את הכרטיס המושלם שלכם?',
    'home.joinProfessionals': 'הצטרפו לכמעט 50,000 מקצוענים שמשתמשים ב-Cardify כדי להרשים את הקשרים שלהם',
    'home.createCardNow': 'צור את הכרטיס שלי עכשיו',
    'home.freeTrial': 'ניסיון חינם - 30 יום',
    'home.exploreExamples': 'חקור דוגמאות',

    // Login page
    'login.title': 'התחברות ל-Cardify',
    'login.noAccount': 'אין לך חשבון עדיין?',
    'login.createAccount': 'צור חשבון',
    'login.emailLabel': 'כתובת אימייל',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordLabel': 'סיסמה',
    'login.passwordPlaceholder': '••••••••',
    'login.signIn': 'התחבר',
    'login.or': 'או',
    'login.backToHome': 'חזרה לבית',
    'login.emailRequired': 'אימייל נדרש',
    'login.emailInvalid': 'פורמט אימייל לא תקין',
    'login.passwordRequired': 'סיסמה נדרשת',
    'login.passwordMin': 'הסיסמה חייבת להכיל לפחות 7 תווים',

    // Register page
    'register.title': 'יצירת חשבון Cardify',
    'register.subtitle': 'הצטרף לקהילת Cardify וצור את כרטיסי הביקור הדיגיטליים שלך',
    'register.haveAccount': 'כבר יש לך חשבון?',
    'register.signIn': 'התחבר',
    'register.firstNameRequired': 'שם פרטי נדרש',
    'register.lastNameRequired': 'שם משפחה נדרש',
    'register.confirmPasswordRequired': 'אישור נדרש',
    'register.passwordMatch': 'הסיסמאות לא תואמות',
    'register.phoneRequired': 'טלפון נדרש',
    'register.phoneInvalid': 'פורמט טלפון לא תקין (למשל: 050-1234567)',
    'register.countryRequired': 'מדינה נדרשת',
    'register.cityRequired': 'עיר נדרשת',
    'register.streetRequired': 'רחוב נדרש',
    'register.houseNumberRequired': 'מספר בית נדרש',
    'register.houseNumberInvalid': 'מספר לא תקין',
    'register.zipRequired': 'מיקוד נדרש',
    'register.zipInvalid': 'מיקוד לא תקין (4-6 ספרות)',
    'register.confirmPasswordLabel': 'אישור סיסמה',
    'register.phoneLabel': 'טלפון',
    'register.addressSection': 'כתובת',
    'register.countryLabel': 'מדינה',
    'register.cityLabel': 'עיר',
    'register.streetLabel': 'רחוב',
    'register.houseNumberLabel': 'מספר בית',
    'register.zipLabel': 'מיקוד',
    'register.personalInfo': 'מידע אישי',
    'register.securityInfo': 'אבטחת החשבון',
    'register.addressInfo': 'כתובת ומיקום',
    'register.accountType': 'סוג חשבון',
    'register.businessAccount': 'חשבון עסקי (יכול ליצור כרטיסים)',
    'register.createAccount': 'צור את החשבון שלי',

    // Profile page
    'profile.title': 'הפרופיל שלי',
    'profile.subtitle': 'נהל את המידע האישי והעדפות שלך',
    'profile.unsavedChanges': 'שינויים לא שמורים (שמירה אוטומטית תתבצע בעוד 2 שניות)',
    'profile.changeAvatar': 'שנה אווטאר',
    'profile.businessAccount': 'חשבון עסקי',
    'profile.personalAccount': 'חשבון אישי',
    'profile.avatarUrl': 'URL של האווטאר',
    'profile.personalInfoSection': 'מידע אישי',
    'profile.addressSection': 'כתובת',
    'profile.businessFeatures': 'חשבון עסקי (גישה לתכונות מקצועיות)',
    'profile.loginRequired': 'עליך להתחבר כדי לראות דף זה.',
    'profile.saving': 'שומר...',
    'profile.saveNow': 'שמור עכשיו',
    'profile.savedAuto': 'הפרופיל נשמר אוטומטית',
    'profile.savedDemo': 'הפרופיל נשמר! (מצב דמו)',
    'profile.saveError': 'שגיאה בשמירת הפרופיל',
    'profile.stateRegion': 'מחוז/אזור',

    // Cards page
    'cards.title': 'הכרטיסים שלי',
    'cards.subtitle': 'נהל את כרטיסי הביקור הדיגיטליים שלך',
    'cards.cardCount': 'כרטיס',
    'cards.cardCountPlural': 'כרטיסים',
    'cards.createCard': 'צור כרטיס',
    'cards.searchPlaceholder': 'חפש בכרטיסים שלך...',
    'cards.loading': 'טוען את הכרטיסים שלך...',
    'cards.loginRequired': 'נדרשת התחברות',
    'cards.loginRequiredDesc': 'עליך להתחבר כדי לראות את הכרטיסים שלך.',
    'cards.signIn': 'התחבר',
    'cards.noCards': 'לא נוצרו כרטיסים',
    'cards.noCardsDesc': 'התחל ביצירת כרטיס הביקור הדיגיטלי הראשון שלך.',
    'cards.createFirstCard': 'צור את הכרטיס הראשון שלי',
    'cards.noResults': 'אין תוצאות',
    'cards.noResultsDesc': 'אף כרטיס לא מתאים לחיפוש שלך',
    'cards.view': 'צפה',
    'cards.likedDemo': 'הכרטיס זכה לאהבה! (מצב דמו)',
    'cards.liked': 'הכרטיס זכה לאהבה!',
    'cards.likeError': 'שגיאה באהבת הכרטיס',
    'cards.deleteConfirm': 'האם אתה בטוח שברצונך למחוק את הכרטיס הזה?',
    'cards.deletedDemo': 'הכרטיס נמחק! (מצב דמו)',
    'cards.deleted': 'הכרטיס נמחק!',
    'cards.deleteError': 'התכונה לא זמינה כעת',

    // Create Card page
    'createCard.title': 'צור כרטיס',
    'createCard.subtitle': 'צור את כרטיס הביקור הדיגיטלי המקצועי החדש שלך',
    'createCard.back': 'חזרה',
    'createCard.loginRequired': 'נדרשת התחברות',
    'createCard.loginRequiredDesc': 'עליך להתחבר כדי ליצור כרטיס.',
    'createCard.signIn': 'התחבר',
    'createCard.businessRequired': 'נדרש חשבון עסקי',
    'createCard.businessRequiredDesc': 'עליך להיות בעל חשבון עסקי כדי ליצור כרטיסי ביקור.',
    'createCard.upgradeToBusiness': 'עדכן לעסקי',
    'createCard.backToCards': 'חזרה לכרטיסים',
    'createCard.basicInfo': 'מידע בסיסי',
    'createCard.cardTitle': 'כותרת הכרטיס',
    'createCard.cardTitlePlaceholder': 'לדוגמה: מפתח Full-Stack',
    'createCard.cardSubtitle': 'כותרת משנה',
    'createCard.cardSubtitlePlaceholder': 'לדוגמה: מומחה React ו-Node.js',
    'createCard.description': 'תיאור',
    'createCard.contact': 'יצירת קשר',
    'createCard.phoneLabel': 'טלפון *',
    'createCard.phonePlaceholder': '050-1234567',
    'createCard.emailLabel': 'אימייל *',
    'createCard.emailPlaceholder': 'contact@example.com',
    'createCard.websiteLabel': 'אתר אינטרנט',
    'createCard.websitePlaceholder': 'https://www.example.com',
    'createCard.address': 'כתובת',
    'createCard.image': 'תמונה (אופציונלי)',
    'createCard.selectImage': 'בחר תמונה',
    'createCard.selectImageAria': 'בחר תמונה לכרטיס',
    'createCard.orEnterUrl': 'או הזן URL של תמונה למטה',
    'createCard.imageUrl': 'URL של התמונה',
    'createCard.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'createCard.imageAlt': 'טקסט חלופי',
    'createCard.imageAltPlaceholder': 'תיאור התמונה',
    'createCard.preview': 'תצוגה מקדימה',
    'createCard.previewTitle': 'כותרת הכרטיס',
    'createCard.previewSubtitle': 'כותרת משנה',
    'createCard.cancel': 'ביטול',
    'createCard.creating': 'יוצר...',
    'createCard.create': 'צור כרטיס',
    'createCard.success': 'הכרטיס נוצר בהצלחה!',
    'createCard.error': 'שגיאה ביצירת הכרטיס',
    'createCard.titleRequired': 'הכותרת נדרשת',
    'createCard.subtitleRequired': 'כותרת המשנה נדרשת',
    'createCard.descriptionRequired': 'התיאור נדרש',
    'createCard.phoneRequired': 'הטלפון נדרש',
    'createCard.emailRequired': 'האימייל נדרש',
    'createCard.countryRequired': 'המדינה נדרשת',
    'createCard.cityRequired': 'העיר נדרשת',
    'createCard.streetRequired': 'הרחוב נדרש',
    'createCard.houseNumberRequired': 'המספר נדרש',
    'createCard.businessOnly': 'רק חשבונות עסקיים יכולים ליצור כרטיסים',
    'createCard.upgradeAccount': 'עדכן לחשבון עסקי',
    'createCard.titleLabel': 'כותרת *',
    'createCard.titlePlaceholder': 'שם החברה או השירות שלך',
    'createCard.subtitleLabel': 'כותרת משנה *',
    'createCard.subtitlePlaceholder': 'התפקיד או ההתמחות שלך',
    'createCard.descriptionLabel': 'תיאור *',
    'createCard.descriptionPlaceholder': 'תאר את הפעילות, השירותים שלך...',

    // CardDetail Page
    'cardDetail.loading': 'טוען...',
    'cardDetail.notFound': 'הכרטיס לא נמצא',
    'cardDetail.notFoundMessage': 'הכרטיס הזה לא קיים או שנמחק.',
    'cardDetail.backToCards': 'חזרה לכרטיסים',
    'cardDetail.description': 'תיאור',
    'cardDetail.contact': 'יצירת קשר',
    'cardDetail.phone': 'טלפון',
    'cardDetail.email': 'אימייל',
    'cardDetail.website': 'אתר אינטרנט',
    'cardDetail.address': 'כתובת',
    'cardDetail.owner': 'בעלים',
    'cardDetail.businessAccount': 'חשבון עסקי',
    'cardDetail.personalAccount': 'חשבון אישי',
    'cardDetail.statistics': 'סטטיסטיקות',
    'cardDetail.likes': 'לייקים',
    'cardDetail.createdOn': 'נוצר ב',
    'cardDetail.actions': 'פעולות',
    'cardDetail.shareCard': 'שתף את הכרטיס הזה',
    'cardDetail.likeCard': 'אהב את הכרטיס הזה',
    'cardDetail.unlikeCard': 'הסר אהבה',
    'cardDetail.editCard': 'ערוך כרטיס',
    'cardDetail.deleteCard': 'מחק כרטיס',
    'cardDetail.loginToLike': 'עליך להתחבר כדי לאהוב כרטיס',
    'cardDetail.likeRemoved': 'האהבה הוסרה',
    'cardDetail.cardLiked': 'הכרטיס זכה לאהבה!',
    'cardDetail.likeError': 'שגיאה באהבת הכרטיס',
    'cardDetail.deleteConfirm': 'האם אתה בטוח שברצונך למחוק את הכרטיס הזה? פעולה זו בלתי הפיכה.',
    'cardDetail.deleteSuccess': 'הכרטיס נמחק בהצלחה',
    'cardDetail.deleteError': 'שגיאה במחיקת הכרטיס',
    'cardDetail.linkCopied': 'הקישור הועתק ללוח',
    'cardDetail.shareError': 'שגיאה בשיתוף הכרטיס',
    'cardDetail.loadError': 'שגיאה בטעינת הכרטיס',
    'cardDetail.user': 'משתמש',
    'cardDetail.phoneCopied': 'מספר הטלפון הועתק!',

    // EditCard Page
    'editCard.title': 'ערוך כרטיס',
    'editCard.subtitle': 'שנה את מידע כרטיס הביקור שלך',
    'editCard.back': 'חזרה',
    'editCard.loginRequired': 'נדרשת התחברות',
    'editCard.loginRequiredDesc': 'עליך להתחבר כדי לערוך כרטיס.',
    'editCard.signIn': 'התחבר',
    'editCard.loading': 'טוען את הכרטיס...',
    'editCard.basicInfo': 'מידע בסיסי',
    'editCard.titleLabel': 'כותרת הכרטיס *',
    'editCard.titlePlaceholder': 'לדוגמה: מפתח Full-Stack',
    'editCard.subtitleLabel': 'כותרת משנה *',
    'editCard.subtitlePlaceholder': 'לדוגמה: מומחה React ו-Node.js',
    'editCard.descriptionLabel': 'תיאור *',
    'editCard.descriptionPlaceholder': 'תאר את השירותים והכישורים שלך...',
    'editCard.contact': 'יצירת קשר',
    'editCard.phoneLabel': 'טלפון *',
    'editCard.phonePlaceholder': '050-1234567',
    'editCard.emailLabel': 'אימייל *',
    'editCard.emailPlaceholder': 'contact@example.com',
    'editCard.websiteLabel': 'אתר אינטרנט',
    'editCard.websitePlaceholder': 'https://mysite.com',
    'editCard.address': 'כתובת',
    'editCard.image': 'תמונה (אופציונלי)',
    'editCard.selectImage': 'בחר תמונה חדשה',
    'editCard.selectImageAria': 'בחר תמונה חדשה לכרטיס',
    'editCard.orModifyUrl': 'או שנה את URL התמונה למטה',
    'editCard.imageUrl': 'URL של התמונה',
    'editCard.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'editCard.imageAlt': 'טקסט חלופי',
    'editCard.imageAltPlaceholder': 'תיאור התמונה',
    'editCard.cancel': 'ביטול',
    'editCard.saving': 'שומר...',
    'editCard.save': 'שמור',
    'editCard.preview': 'תצוגה מקדימה',
    'editCard.previewTitle': 'כותרת הכרטיס',
    'editCard.previewSubtitle': 'כותרת משנה',
    'editCard.success': 'הכרטיס עודכן בהצלחה!',
    'editCard.successDemo': 'הכרטיס עודכן בהצלחה! (מצב דמו)',
    'editCard.error': 'שגיאה בעדכון הכרטיס',
    'editCard.formError': 'אנא תקן את השגיאות בטופס',
    'editCard.checkDataError': 'בדוק את הנתונים שלך ונסה שוב',
    'editCard.titleRequired': 'הכותרת נדרשת',
    'editCard.subtitleRequired': 'כותרת המשנה נדרשת',
    'editCard.descriptionRequired': 'התיאור נדרש',
    'editCard.phoneRequired': 'הטלפון נדרש',
    'editCard.phoneInvalid': 'פורמט טלפון לא תקין (לדוגמה: 050-1234567)',
    'editCard.emailRequired': 'האימייל נדרש',
    'editCard.emailInvalid': 'פורמט אימייל לא תקין',
    'editCard.countryRequired': 'המדינה נדרשת',
    'editCard.cityRequired': 'העיר נדרשת',
    'editCard.streetRequired': 'הרחוב נדרש',
    'editCard.houseNumberRequired': 'מספר הבית נדרש',
    'editCard.loadError': 'שגיאה בטעינת הכרטיס',
    'editCard.notAuthorized': 'אינך מורשה לערוך את הכרטיס הזה',

    // Loading & UI Components
    'loading.default': 'טוען...',
    'loading.page': 'טוען את הדף...',
    'loading.data': 'טוען נתונים...',
    'loading.saving': 'שומר...',
    'loading.processing': 'מעבד...',

    // NotFound Page
    'notFound.title': 'הדף לא נמצא',
    'notFound.message': 'מצטערים, הדף שאתה מחפש לא קיים או שהועבר.',
    'notFound.backHome': 'חזרה לבית',
    'notFound.backPrevious': 'דף קודם',
    'notFound.popularPages': 'הדפים הפופולריים ביותר:',
    'notFound.myCards': 'הכרטיסים שלי',
    'notFound.createCard': 'צור כרטיס',
    'notFound.myProfile': 'הפרופיל שלי',

    // AdminDashboard
    'admin.title': 'לוח בקרה למנהל',
    'admin.subtitle': 'ניהול ומעקב של פלטפורמת Cardify',
    'admin.accessDenied': 'גישה נדחתה',
    'admin.adminOnly': 'רק מנהלים יכולים לגשת לעמוד זה.',
    'admin.loading': 'טוען לוח בקרה של מנהל...',
    'admin.totalUsers': 'סך משתמשים',
    'admin.activeUsers': 'משתמשים פעילים',
    'admin.totalCards': 'סך כרטיסים',
    'admin.recentSignups': 'הרשמות חדשות',
    'admin.userManagement': 'ניהול משתמשים',
    'admin.refresh': 'רענן',
    'admin.searchUsers': 'חפש משתמש...',
    'admin.filterUsers': 'סנן משתמשים לפי סטטוס',
    'admin.allUsers': 'כל המשתמשים',
    'admin.activeOnly': 'משתמשים פעילים',
    'admin.inactiveOnly': 'משתמשים לא פעילים',
    'admin.user': 'משתמש',
    'admin.type': 'סוג',
    'admin.status': 'סטטוס',
    'admin.cards': 'כרטיסים',
    'admin.lastLogin': 'התחברות אחרונה',
    'admin.actions': 'פעולות',
    'admin.business': 'עסקי',
    'admin.personal': 'אישי',
    'admin.active': 'פעיל',
    'admin.inactive': 'לא פעיל',
    'admin.never': 'אף פעם',
    'admin.admin': 'מנהל',
    'admin.activityLog': 'יומן פעילות',
    'admin.noActivity': 'אין פעילות אחרונה',
    'admin.userActivated': 'הופעל',
    'admin.userDeactivated': 'הושבת',
    'admin.userDeleted': 'נמחק',
    'admin.actionSuccess': 'משתמש {action} בהצלחה',
    'admin.actionError': 'לא ניתן לבצע פעולה זו',
    'admin.newUserCreated': 'משתמש חדש נוצר',
    'admin.newCardCreated': 'כרטיס חדש נוצר',
    'admin.userLogin': 'התחברות משתמש',
    'admin.adminAction': 'פעולת מנהל בוצעה',

    // Export/Import Page
    'exportImport.title': 'יצוא/יבוא',
    'exportImport.loadError': 'שגיאה',
    'exportImport.loadErrorMsg': 'לא ניתן לטעון את הכרטיסים שלך',
    'exportImport.noCardsTitle': 'אין כרטיסים לייצוא',
    'exportImport.noCardsMsg': 'אתה צריך לפחות כרטיס אחד כדי לייצא',
    'exportImport.exportSuccess': 'יצוא הצליח',
    'exportImport.exportSuccessMsg': '{count} כרטיסים יוצאו בפורמט {format}',
    'exportImport.importPartial': 'יבוא חלקי',
    'exportImport.importPartialMsg': '{count} שגיאות במהלך היבוא',
    'exportImport.importError': 'שגיאת יבוא',
    'exportImport.importErrorMsg': 'שגיאה במהלך היבוא',
    'exportImport.chooseFile': 'בחר קובץ JSON לייבוא',
    'exportImport.unknownError': 'שגיאה לא ידועה',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Récupérer la langue depuis localStorage ou utiliser 'fr' par défaut
    const savedLanguage = localStorage.getItem('cardify-language') as Language;
    return savedLanguage || 'fr';
  });

  // Sauvegarder la langue dans localStorage quand elle change
  useEffect(() => {
    // Sauvegarder la langue dans localStorage
    localStorage.setItem('cardify-language', language);
    
    // Apply RTL for Hebrew
    if (language === 'he') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'he';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  // Fonction de traduction
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
